# -*- coding: utf-8 -*-
"""Python day 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PjyIyr-FG7hUh97Vk9LxnV61PvqqNLc
"""

from sklearn.metrics import confusion_matrix
actual = [1, 0, 1, 1, 0, 1]
predicted = [1, 1, 1, 0, 0, 0]
confusion_Matrix = confusion_matrix(actual, predicted)


print("Confusion Matrix:\n", confusion_Matrix)
print("True Positive (TP):", TP)
print("True Negative (TN):", TN)
print("False Positive (FP):", FP)
print("False Negative (FN):", FN)







